//! Thin NSPasteboard wrapper. Talks to AppKit through `mitchellh/zig-objc`,
//! whose `msgSend(Return, sel, .{args})` synthesizes the right `objc_msgSend`
//! cast per call site — including the struct-return variants x86_64 needs.

const std = @import("std");
const objc = @import("objc");

// ---- NSString conversion helpers --------------------------------------------

// Autoreleased — don't hold past the current pool's deinit.
fn nsStringFromCStr(s: [*:0]const u8) objc.Object {
    const NSString = objc.getClass("NSString").?;
    return NSString.msgSend(objc.Object, "stringWithUTF8String:", .{s});
}

fn nsStringFromSlice(allocator: std.mem.Allocator, s: []const u8) !objc.Object {
    const z = try allocator.dupeSentinel(u8, s, 0);
    defer allocator.free(z);
    return nsStringFromCStr(z.ptr);
}

fn cStrFromNSString(ns: objc.Object) ?[*:0]const u8 {
    if (ns.value == null) return null;
    return ns.msgSend([*:0]const u8, "UTF8String", .{});
}

// ---- Public API -------------------------------------------------------------

pub const Pasteboard = struct {
    pb: objc.Object,

    /// Set by `zclip use`; the daemon skips entries carrying it, which is what
    /// keeps `use` from feeding its own writes back into history.
    pub const origin_type: [*:0]const u8 = "dev.zclip.origin";

    /// 1Password, Bitwarden, Keychain etc. mark sensitive items with this for
    /// history tools to skip.
    pub const concealed_type: [*:0]const u8 = "org.nspasteboard.ConcealedType";

    /// Tool-generated entries, not user copied.
    pub const auto_generated_type: [*:0]const u8 = "org.nspasteboard.AutoGeneratedType";

    /// What `NSPasteboardTypeString` resolves to at runtime.
    pub const string_type: [*:0]const u8 = "public.utf8-plain-text";

    /// A pasteboard image flavour, plus how we persist it.
    pub const ImageType = struct {
        /// Type the bytes are read/written under, and what lands in
        /// `images.uti`. Sentinel-terminated: consumers want either an NSString
        /// bridge (`.ptr`) or a SQLite bind (`.len`).
        uti: [:0]const u8,
        /// Filename suffix for the original on disk — `public.png` isn't one.
        ext: []const u8,
    };

    /// One copy usually lands under several flavours at once (screenshots
    /// publish TIFF and PNG both), and whichever wins here is what gets hashed
    /// and archived. PNG first: lossless and far smaller than TIFF. JPEG last —
    /// it only appears alone.
    const image_types = [_]ImageType{
        .{ .uti = "public.png", .ext = "png" },
        .{ .uti = "public.tiff", .ext = "tiff" },
        .{ .uti = "public.jpeg", .ext = "jpg" },
    };

    /// First image flavour the pasteboard offers, or null if it holds none.
    pub fn imageType(self: Pasteboard) ?ImageType {
        for (image_types) |t| {
            if (self.hasType(t.uti.ptr)) return t;
        }
        return null;
    }

    /// `.?` panics if NSPasteboard is missing — a linker/SDK bug, not a
    /// recoverable condition.
    pub fn general() Pasteboard {
        const NSPasteboard = objc.getClass("NSPasteboard").?;
        const pb = NSPasteboard.msgSend(objc.Object, "generalPasteboard", .{});
        return .{ .pb = pb };
    }

    /// Increments on every write — a "did anything change?" probe that doesn't
    /// read content.
    pub fn changeCount(self: Pasteboard) i64 {
        return @intCast(self.pb.msgSend(c_long, "changeCount", .{}));
    }

    pub fn hasType(self: Pasteboard, wanted: [*:0]const u8) bool {
        const wanted_ns = nsStringFromCStr(wanted);

        const types = self.pb.msgSend(objc.Object, "types", .{});
        if (types.value == null) return false;

        const count = types.msgSend(c_long, "count", .{});

        var i: c_long = 0;
        while (i < count) : (i += 1) {
            const item = types.msgSend(objc.Object, "objectAtIndex:", .{i});
            if (item.msgSend(bool, "isEqualToString:", .{wanted_ns})) return true;
        }
        return false;
    }

    pub fn hasConcealed(self: Pasteboard) bool {
        return self.hasType(concealed_type);
    }

    pub fn hasAutoGenerated(self: Pasteboard) bool {
        return self.hasType(auto_generated_type);
    }

    pub fn hasOrigin(self: Pasteboard) bool {
        return self.hasType(origin_type);
    }

    /// Plain-text content, or null if the pasteboard holds no string. Caller
    /// owns the returned slice.
    pub fn readString(self: Pasteboard, allocator: std.mem.Allocator) !?[]u8 {
        const t = nsStringFromCStr(string_type);
        const ns = self.pb.msgSend(objc.Object, "stringForType:", .{t});
        const cstr = cStrFromNSString(ns) orelse return null;
        const slice = std.mem.span(cstr);
        // MUST copy: the NSString is autoreleased, so its storage dies at the
        // next pool drain.
        return try allocator.dupe(u8, slice);
    }

    /// Raw bytes for `ty`, or null if the pasteboard has no data under it.
    /// Caller owns the returned slice.
    pub fn readData(
        self: Pasteboard,
        allocator: std.mem.Allocator,
        ty: [*:0]const u8,
    ) !?[]u8 {
        const t = nsStringFromCStr(ty);
        const data = self.pb.msgSend(objc.Object, "dataForType:", .{t});
        if (data.value == null) return null;

        // `length` is NSUInteger, hence c_ulong.
        const len: usize = @intCast(data.msgSend(c_ulong, "length", .{}));
        if (len == 0) return null;
        const ptr = data.msgSend([*]const u8, "bytes", .{});
        // MUST copy, same contract as readString: the NSData is autoreleased.
        return try allocator.dupe(u8, ptr[0..len]);
    }

    /// Replace pasteboard contents with `content`, tagged `dev.zclip.origin` so
    /// the daemon skips this write.
    ///
    /// Returns AppKit's verdict: `setString:forType:` answers NO when the type
    /// was never declared for the current change count, a real failure to write.
    /// Callers must not report success on false.
    pub fn writeStringAsOrigin(self: Pasteboard, allocator: std.mem.Allocator, content: []const u8) !bool {
        _ = self.pb.msgSend(c_long, "clearContents", .{});
        self.markOrigin();

        const content_ns = try nsStringFromSlice(allocator, content);
        const string_t = nsStringFromCStr(string_type);
        return self.pb.msgSend(bool, "setString:forType:", .{ content_ns, string_t });
    }

    /// Image counterpart of `writeStringAsOrigin`: `bytes` go on under `ty`
    /// (the UTI it was archived as), origin-tagged, same return contract.
    pub fn writeDataAsOrigin(self: Pasteboard, bytes: []const u8, ty: [*:0]const u8) bool {
        _ = self.pb.msgSend(c_long, "clearContents", .{});
        self.markOrigin();

        const NSData = objc.getClass("NSData").?;
        // dataWithBytes:length: copies, so `bytes` needn't outlive this call.
        // @intCast, not a bare @as: usize and NSUInteger match on every Apple
        // target we build for, but that's a target fact, not a language one.
        const data = NSData.msgSend(objc.Object, "dataWithBytes:length:", .{
            bytes.ptr,
            @as(c_ulong, @intCast(bytes.len)),
        });
        const t = nsStringFromCStr(ty);
        return self.pb.msgSend(bool, "setData:forType:", .{ data, t });
    }

    // Called before the content in both writers above: each set* bumps
    // changeCount, so the daemon can poll mid-write. Content-first would expose
    // a {content, no-tag} item it captures as its own (feedback loop);
    // tag-first leaves only skippable transients. The value is arbitrary —
    // only the type's presence matters.
    fn markOrigin(self: Pasteboard) void {
        const origin_ns = nsStringFromCStr("1");
        const origin_t = nsStringFromCStr(origin_type);
        self.pb.msgSend(void, "setString:forType:", .{ origin_ns, origin_t });
    }
};
